-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "stopLossPercent" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ADD COLUMN     "takeProfitPercent" DOUBLE PRECISION NOT NULL DEFAULT 50.0,
ALTER COLUMN "pollingInterval" SET DEFAULT 60;
